name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["kind/enhancement", "status/need-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input on making AINative Studio better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative approaches...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Provide a specific example.
      placeholder: |
        1. As a [user type]
        2. I want to [action]
        3. So that [benefit]
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area would this feature affect?
      options:
        - Frontend (UI/Components)
        - Backend (API/Services)
        - SEO/Metadata
        - Performance
        - Accessibility
        - DevOps/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - P1 - High (Critical for my workflow)
        - P2 - Medium (Would be very helpful)
        - P3 - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or links to similar implementations
      placeholder: Drag and drop images or paste URLs...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, dependencies, or considerations you're aware of?
      placeholder: Technical notes...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with design/mockups
        - label: I can help with testing

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests and this is not a duplicate
          required: true
        - label: I have provided a clear use case
          required: true
        - label: This feature aligns with the project's goals
          required: true
