import type {
  OpenClawAgent,
  OpenClawTemplate,
  Integration,
  Channel,
  TeamMember,
  ApiKeyProvider,
} from '@/types/openclaw';

export const MOCK_AGENTS: OpenClawAgent[] = [
  {
    id: 'agent-001',
    name: 'Linear Ticket Solver',
    persona: 'Monitors Linear for assigned issues. Creates a feature branch, implements the solution, pushes the code, and opens a pull request for your team to review.',
    model: 'anthropic/claude-opus-4-5',
    userId: 'user-001',
    status: 'running',
    openclawSessionKey: 'agent:web:linear-ticket-solver',
    openclawAgentId: 'oc_001',
    heartbeatEnabled: true,
    heartbeatInterval: '5m',
    heartbeatChecklist: [
      'Check Linear for newly assigned or in-progress issues',
      'For each issue: create branch, implement fix, push, and open PR',
      'Post PR link to Slack with a summary of changes',
    ],
    lastHeartbeatAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    nextHeartbeatAt: new Date(Date.now() + 300000).toISOString(),
    configuration: {},
    errorMessage: null,
    errorCount: 0,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    provisionedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    pausedAt: null,
    stoppedAt: null,
  },
  {
    id: 'agent-002',
    name: 'Team Slack Engineer',
    persona: 'A virtual AI engineer on your team who can talk in Slack. Investigates code, answers technical questions, and helps debug.',
    model: 'anthropic/claude-opus-4-5',
    userId: 'user-001',
    status: 'running',
    openclawSessionKey: 'agent:web:team-slack-engineer',
    openclawAgentId: 'oc_002',
    heartbeatEnabled: true,
    heartbeatInterval: '5m',
    heartbeatChecklist: ['Monitor Slack channels for questions', 'Review open PRs'],
    lastHeartbeatAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    nextHeartbeatAt: new Date(Date.now() + 300000).toISOString(),
    configuration: {},
    errorMessage: null,
    errorCount: 0,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    provisionedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    pausedAt: null,
    stoppedAt: null,
  },
  {
    id: 'agent-003',
    name: 'Outreach & Networking',
    persona: 'Handles outreach campaigns, manages LinkedIn connections, and nurtures networking relationships.',
    model: 'anthropic/claude-opus-4-5',
    userId: 'user-001',
    status: 'running',
    openclawSessionKey: 'agent:web:outreach-networking',
    openclawAgentId: 'oc_003',
    heartbeatEnabled: true,
    heartbeatInterval: '30m',
    heartbeatChecklist: ['Check for new connection requests', 'Send follow-up messages'],
    lastHeartbeatAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    nextHeartbeatAt: new Date(Date.now() + 1800000).toISOString(),
    configuration: {},
    errorMessage: null,
    errorCount: 0,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    provisionedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    pausedAt: null,
    stoppedAt: null,
  },
  {
    id: 'agent-004',
    name: 'Debo',
    persona: 'A general-purpose AI assistant for day-to-day tasks.',
    model: 'anthropic/claude-opus-4-5',
    userId: 'user-001',
    status: 'running',
    openclawSessionKey: 'agent:web:debo',
    openclawAgentId: 'oc_004',
    heartbeatEnabled: false,
    heartbeatInterval: null,
    heartbeatChecklist: null,
    lastHeartbeatAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    nextHeartbeatAt: null,
    configuration: {},
    errorMessage: null,
    errorCount: 0,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    provisionedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    pausedAt: null,
    stoppedAt: null,
  },
  {
    id: 'agent-005',
    name: 'Atlas',
    persona: 'A project management AI that tracks progress, assigns tasks, and generates reports.',
    model: 'anthropic/claude-opus-4-5',
    userId: 'user-001',
    status: 'running',
    openclawSessionKey: 'agent:web:atlas',
    openclawAgentId: 'oc_005',
    heartbeatEnabled: true,
    heartbeatInterval: '1h',
    heartbeatChecklist: ['Check project milestones', 'Generate daily status report'],
    lastHeartbeatAt: new Date(Date.now() - 13 * 3600000).toISOString(),
    nextHeartbeatAt: new Date(Date.now() + 3600000).toISOString(),
    configuration: {},
    errorMessage: null,
    errorCount: 0,
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 13 * 3600000).toISOString(),
    provisionedAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    pausedAt: null,
    stoppedAt: null,
  },
];

export const MOCK_TEMPLATES: OpenClawTemplate[] = [
  {
    id: 'template-linear',
    name: 'Linear Ticket Solver',
    description: 'Automatically picks up assigned Linear issues, writes the code fix, and opens a pull request for your team to review.',
    category: 'engineering',
    icons: ['github', 'linear', 'git'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are a software engineer that monitors Linear for assigned issues...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Check Linear for newly assigned or in-progress issues', 'For each issue: create branch, implement fix, push, and open PR', 'Post PR link to Slack with a summary of changes'],
  },
  {
    id: 'template-pr-review',
    name: 'PR Review Bot',
    description: 'Watches your open pull requests for review comments, addresses feedback automatically, and re-requests reviews.',
    category: 'engineering',
    icons: ['github'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are a code reviewer that monitors GitHub PRs...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Check for new PR review comments', 'Address feedback and push fixes'],
  },
  {
    id: 'template-incident-responder',
    name: 'Incident Responder',
    description: 'Responds to Grafana alerts by investigating distributed traces, logs, and metrics to deliver a root-cause analysis.',
    category: 'engineering',
    icons: ['grafana', 'pagerduty'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are an incident responder that monitors Grafana alerts...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Check for active Grafana alerts', 'Investigate distributed traces and logs'],
  },
  {
    id: 'template-log-monitor',
    name: 'Log Monitor',
    description: 'Continuously monitors your backend application logs for errors, exceptions, and anomalous patterns before they become incidents.',
    category: 'engineering',
    icons: ['grafana'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are a log monitoring agent...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Scan application logs for errors', 'Alert on anomalous patterns'],
  },
  {
    id: 'template-http-error',
    name: 'HTTP Error Monitoring',
    description: 'Monitors HTTP response codes across your services and alerts with root-cause analysis on errors.',
    category: 'devops-infrastructure',
    icons: ['grafana'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You monitor HTTP endpoints for errors...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Check HTTP response codes', 'Alert on 5xx errors with analysis'],
  },
  {
    id: 'template-slack-engineer',
    name: 'Team Slack Engineer',
    description: 'A virtual AI engineer your team can talk to in Slack. Investigates code, answers technical questions with real codebase context.',
    category: 'engineering',
    icons: ['slack'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are a virtual engineer available in Slack...',
    defaultHeartbeatInterval: '5m',
    defaultChecklist: ['Monitor Slack channels for questions'],
  },
  {
    id: 'template-on-call',
    name: 'On-Call Companion',
    description: 'You can call assistant when you are away from your laptop. Diagnose production issues, create fix PRs, and manage incidents via phone.',
    category: 'devops-infrastructure',
    icons: ['pagerduty', 'twilio'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You are an on-call companion...',
    defaultHeartbeatInterval: '15m',
    defaultChecklist: ['Check for active incidents', 'Prepare diagnostic reports'],
  },
  {
    id: 'template-sdk-outreach',
    name: 'SDK Outreach Agent',
    description: 'Manages outbound developer outreach campaigns and follow-ups.',
    category: 'sales-outreach',
    icons: ['linkedin', 'email'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You manage developer outreach...',
    defaultHeartbeatInterval: '30m',
    defaultChecklist: ['Check for new outreach targets', 'Send follow-up messages'],
  },
  {
    id: 'template-customer-support',
    name: 'Customer Support',
    description: 'Prototyping, support, and relationship management.',
    category: 'sales-outreach',
    icons: ['email', 'slack'],
    defaultModel: 'anthropic/claude-opus-4-5',
    defaultPersona: 'You handle customer support inquiries...',
    defaultHeartbeatInterval: '15m',
    defaultChecklist: ['Check for new support tickets', 'Respond to pending inquiries'],
  },
];

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    icon: 'gmail',
    description: 'Receive emails and forward them to your agent for processing.',
    connected: false,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    description: 'Post content, read profiles, send messages (via browser), and manage connections.',
    connected: false,
    comingSoon: true,
  },
];

export const MOCK_CHANNELS: Channel[] = [
  {
    id: 'slack',
    name: 'Slack',
    icon: 'slack',
    description: 'Connect to Slack workspaces via Socket Mode or HTTP Events API.',
    connected: false,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: 'telegram',
    description: 'Connect a Telegram bot. Fastest to set up \u2014 just a bot token from @BotFather.',
    connected: false,
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: 'whatsapp',
    description: 'Connect to WhatsApp by scanning a QR code.',
    connected: false,
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: 'discord',
    description: 'Connect a Discord bot to servers, channels, and DMs.',
    connected: false,
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    icon: 'teams',
    description: 'Connect to Microsoft Teams via the Bot Framework (plugin-based channel).',
    connected: false,
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'member-001',
    name: 'Toby Morning',
    email: 'toby@ainative.studio',
    role: 'owner',
    avatarInitials: 'TM',
  },
];

export const MOCK_API_KEY_PROVIDERS: ApiKeyProvider[] = [
  { id: 'anthropic', name: 'Anthropic', configured: false },
  { id: 'google-ai', name: 'Google AI', configured: false },
  { id: 'mistral', name: 'Mistral', configured: false },
  { id: 'venice-ai', name: 'Venice AI', configured: false },
  { id: 'minimax', name: 'MiniMax', configured: false },
  { id: 'openai', name: 'OpenAI', configured: false },
  { id: 'openrouter', name: 'OpenRouter', configured: false },
  { id: 'groq', name: 'Groq', configured: false },
  { id: 'moonshot-ai', name: 'Moonshot AI', configured: false },
  { id: '2-ai', name: '2.AI', configured: false },
  { id: 'cerebras', name: 'Cerebras', configured: false },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'engineering', label: 'Engineering' },
  { id: 'sales-outreach', label: 'Sales & Outreach' },
  { id: 'devops-infrastructure', label: 'DevOps & Infrastructure' },
  { id: 'productivity', label: 'Productivity' },
] as const;
